### ISSUE TITLE
Incorrect indentation error message for conditionals

### ISSUE THREAD

**Issue by rtfeldman** [elm/error-message-catalog#14]
The following compiles successfully:

``` elm
module Main where

one = if True then 1
              else 0
```

If you delete the indentation on the last line, you get:

``` elm
module Main where

one = if True then 1
else 0
```

```
## ERRORS in Main.elm ##########################################################

-- SYNTAX PROBLEM ----------------------------------------------------- Main.elm

I ran into something unexpected when parsing your code!

4| else 0
   ^
I am looking for one of the following things:

    an 'else' branch
    whitespace
```

As reported in https://github.com/elm-lang/elm-platform/issues/16, this situation came up when someone was working through a tutorial on conditionals.

The current message seems confusing because it points to the word `else` and says that this is invalid, but `an 'else' branch` would have been acceptable.

**Comment by evancz** [comment]
It is improved in 0.19.1 with the following message:

```
-- UNFINISHED IF ------------------------------------------------------ temp.elm

I was expecting to see an `else` branch after this:

2| one = if True then 1
                       ^
I know what to do when the condition is `True`, but not when it is `False`.

Add an else branch to handle that scenario!
```

I think this message will be relatively common with people not knowing that an `else` is needed, so I wouldn't want to clutter the message for this particular scenario. It may be possible to detect it specifically though. I'll give it a shot.

**Comment by evancz** [comment]
Added a tweak in https://github.com/elm/compiler/commit/98b963c43a45b7296c4ed957ec01e578efe51294 to produce:

```
-- WEIRD ELSE BRANCH -------------------------------------------------- temp.elm

I was partway through an `if` expression when I got stuck here:

1| one = if True then 1
2| else 0
   ^^^^
I think this else keyword needs to be indented more. Try adding some spaces
before it.
```

It also works for code like:

```elm

one =
  let
    number =
      if True then 1
   else 0
  in
  41
```

I don't really expect that kind of thing to happen, but it's nicer anyway!

**Comment by rtfeldman** [comment]
😻 awesome, thank you!
